# Android CircleCI configuration file
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      # Instruct Gradle to download all the dependencies, such as libraries
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      # Save the downloaded Gradle info to a cache to speed-up future builds
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      # Generate an APK file
      - run:
          name: Assemble Debug Build
          command: ./gradlew assembleDebug
      # Store the APK file
      - store_artifacts:
          path: app/build/outputs/apk/dev/debug/app-dev-debug.apk
          destination: apks/fetan-dev-debug.apk